version: "3.9"
services:
  db:
    image: pgvector/pgvector:pg16
    container_name: rag_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ragdb
    ports:
      - "5432:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ..
      dockerfile: infra/Dockerfile.backend
    container_name: rag_backend
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ../backend:/app  # Kodları volume ile mount et → hot reload için kolaylık

volumes:
  pgdata:
